name: Run MATLAB Tests on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Deep_Learning_Toolbox Statistics_and_Machine_Learning_Toolbox Parallel_Computing_Toolbox Deep_Learning_Toolbox_Model_for_GoogLeNet_Network
          release: R2024b
          cache: true
      - name: Install XFCE and TigerVNC
        run: |
         sudo apt-get update
         sudo apt-get install -y xfce4 xfce4-goodies tigervnc-standalone-server
      - name: Set up VNC password
        run: |
          mkdir -p ~/.vnc
          echo "${{ secrets.VNC_PASSWORD }}" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
      - name: Start VNC server
        run: |
          vncserver :1 -geometry 1920x1080 -depth 24
          sleep 5
          echo "vncserver started on display :1"
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        env:
           DISPLAY: :1
        with:
          source-folder: .
          select-by-folder: tests
          strict: true
          logging-level: detailed
          test-results-pdf: test-results/results.pdf
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-results/results.xml
            code-coverage/coverage.xml          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: code-coverage/coverage.xml
      - name: Stop VNC server
        if: always()
        run: vnvserver -kill :1